secret_key_base: c953f195d2098eaedda355d9ded748f5373c6ae58e8d02c060550753ab2d2bf53a05e491586a4c1293ff46b2904099c8e552b7efc8eeb9782ec8b58ebfe4faa2

database:
  username:
    development: 'dev_db_username'
    production: 'prod_db_username'
  password:
    development: 'dev_db_password'
    production: 'prod_db_password'
  name:
    production: 'gse_prod'
email:
  user_name: 'google_user_email'
  password: 'google_user_password'
  prod_host: ''
heroku:
  production: 'true'
